##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.10.0-B14] date: [Wed Jan 20 23:10:21 CST 2021] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = ucosii_cm0_basic


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = ./build

######################################
# source
######################################
# C sources
C_SOURCES = \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/usart.c \
Core/Src/stm32f0xx_it.c \
Core/Src/stm32f0xx_hal_msp.c \
Core/Src/stm32f0xx_hal_timebase_tim.c \
Core/Src/system_stm32f0xx.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_exti.c	\
rtos/uC-CPU/cpu_core.c \
rtos/uC-CPU/ARM-Cortex-M/ARMv6-M/cpu_c.c \
rtos/uC-OS2/Source/os_core.c \
rtos/uC-OS2/Source/os_flag.c \
rtos/uC-OS2/Source/os_mbox.c \
rtos/uC-OS2/Source/os_mutex.c \
rtos/uC-OS2/Source/os_q.c \
rtos/uC-OS2/Source/os_sem.c \
rtos/uC-OS2/Source/os_task.c \
rtos/uC-OS2/Source/os_time.c \
rtos/uC-OS2/Source/os_tmr.c \
rtos/uC-OS2/Cfg/Template/app_hooks.c \
rtos/uC-OS2/Ports/os_cpu_c.c \
rtos/uC-OS2/Ports/os_dbg.c \
rtos/uC-LIB/lib_ascii.c \
rtos/uC-LIB/lib_math.c \
rtos/uC-LIB/lib_mem.c \
rtos/uC-LIB/lib_str.c \
utils/utils.c \
common/print.c

# ASM sources
ASM_SOURCES = \
startup_stm32f030x8.s \
rtos/uC-OS2/Ports/os_cpu_a.s \
rtos/uC-CPU/ARM-Cortex-M/ARMv6-M/GNU/cpu_a.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

# map (address sorted)
NM = $(PREFIX)nm -n -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F030x8 \

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F0xx_HAL_Driver/Inc \
-IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F0xx/Include \
-IDrivers/CMSIS/Include	\
-Irtos/uC-CPU \
-Irtos/uC-CPU/Cfg/Template \
-Irtos/uC-CPU/ARM-Cortex-M/ARMv6-M/GNU \
-Irtos/uC-OS2/Cfg/Template \
-Irtos/uC-OS2/Ports \
-Irtos/uC-OS2/Source \
-Irtos/uC-LIB/Cfg/Template \
-Irtos/uC-LIB \
-Iutils	\
-Icommon


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F030R8Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin map


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	

$(BUILD_DIR):
	mkdir $@

map:
	$(NM) $(BUILD_DIR)/$(TARGET).elf > $(BUILD_DIR)/System.map
	
#######################################
# clean up
#######################################
clean:
ifeq ($(OS), Windows_NT)
	@rmdir /s $(BUILD_DIR)
else
	@rm -rf $(BUILD_DIR)
endif

#######################################
# download image

# openocd -s search scripts or set
# OPENOCD_SCRIPTS environmet variable
#######################################
load:
	openocd \
		-c "tcl_port disabled" \
		-c "gdb_port 3333" \
		-c "telnet_port 4444" \
		-f "st_nucleo_f0.cfg" \
		-c "program $(BUILD_DIR)/$(TARGET).elf"	\
		-c "reset" \
		-c "shutdown"

#######################################
# debug
#######################################
debug:
	openocd	\
		-c "tcl_port disabled" \
		-c "gdb_port 3333" \
		-c "telnet_port 4444" \
		-f "st_nucleo_f0.cfg" \
		-c "program $(BUILD_DIR)/$(TARGET).elf"	\
		-c "init" \
		-c "halt"
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
